# Generated by Django 6.1 on 2026-08-11 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=10)),
                ('roll_number', models.IntegerField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(default='students/default.png', upload_to='students/photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='students/qr/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
