# Generated by Django 6.1 on 2026-08-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA (Bachelor of Computer Applications)'), ('BCS', 'BCS (Bachelor of Computer Science)'), ('BBA', 'BBA (Bachelor of Business Administration)'), ('MSC', 'M.Sc. (Master of Science)'), ('BSC', 'B.Sc. (Bachelor of Science)')], default='BCA', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(default='Computer Science & IT', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='division',
            field=models.CharField(choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year')], default='Third Year', max_length=50),
        ),
    ]
