# Generated by Django 6.1 on 2026-08-11 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(default='BCA', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='division',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(default='Third Year', max_length=50),
        ),
    ]
