# Generated by Django 6.1 on 2026-08-13 09:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_announcementnotice_bannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(default='students/default.png', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='students/photos/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='students/qr/'),
        ),
    ]
