# Generated by Django 6.1 on 2026-08-13 09:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
