# Generated by Django 6.1 on 2026-08-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_studentprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('certificate_type', models.CharField(choices=[('Event Participation', 'Event Participation'), ('Academic Excellence', 'Academic Excellence'), ('Course Completion', 'Course Completion'), ('Sports & Extra Curricular', 'Sports & Extra Curricular')], default='Event Participation', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.studentprofile')),
            ],
        ),
    ]
