# Generated by Django 6.1 on 2026-08-14 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(default='Computer Science & IT', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('assigned_course', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_year', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_division', models.CharField(default='A', max_length=10)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
