# Generated by Django 6.1 on 2026-08-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacherprofile_dailyclassattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
