# Generated by Django 6.1 on 2026-08-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_delete_teacherprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyclassattendance',
            options={'ordering': ['-date', '-marked_at']},
        ),
    ]
